### ISSUE TITLE
KL loss is extremely large

### ISSUE THREAD

**Issue by facetohard** [sinhasam/vaal#10]
I tried to implement the vaal on cityscapes.
The setting of experiment is:
resolution: 256 * 256
VAE laten dim(z): 128
lr: 5e-4
Have you met the same condition？

**Comment by sinhasam** [comment]
Yes we did, and we had to tune the parameters, but the large KL is expected since we are not trying to learn a good latent, but instead a representation which tricks the discriminator. The latent dimension of 128 worked reasonably well.

**Comment by facetohard** [comment]
How did you tune the parameters? I tried to train VAE only and got 'nan' loss after few iterations.

**Comment by yxwang-10** [comment]
@facetohard I had the same problem when training on ImageNet. You can reduce the lr of the VAE's optim.And the learning rate I use is 5e-6.
