### ISSUE TITLE
epoch and train_iterations 

### ISSUE THREAD

**Issue by sweetTT** [sinhasam/vaal#11]
Is the epoch in your paper the same as train_iterations in your code? I find that the default value of train_iterations in your code is 100000. Should I change it to 100? By the way, how long does it take for you to run a cifar10 experiment in your environment?

**Comment by qa8306202** [comment]
When I use 1000 iters, data=0.1 ,the acc = 44.51%
When I use 10000, data = 0.1, the acc = 69.83%
I dont know the train_iterations too?
How can I get the results in your paper?

**Comment by sinhasam** [comment]
I changed something to make the training a bit more stable (less difference between runs) but i will patch the change to go back. Will patch it up shortly. Thanks !
