### ISSUE TITLE
About train_iteration in every cycle

### ISSUE THREAD

**Issue by lmh0921** [sinhasam/vaal#17]
Hello,

I have some questions about:
In the code Solver.py->def train
`self.args.train_iterations = (self.args.num_images * self.args.train_epochs) // self.args.batch_size`

However, in each cycle, for example, from budget 5000 to 7500, the `self.args.num_images` is always 50000 for cifar10, should not it be the number of current labeled data number like 7500? Because in each cycle, the train data is only the labeled data instead of the whole dataset with size 50000.

Thank you

**Comment by sinhasam** [comment]
This seems to stabilize test performance, I noticed that otherwise the variance was very large between runs otherwise, which made it hard to report with.
