### ISSUE TITLE
Total time 

### ISSUE THREAD

**Issue by manza-ari** [sinhasam/vaal#18]
how long it will take to retrain all the models? I am running main.py for more than one week.

**Comment by sinhasam** [comment]
It should not take that long. There used to be problems with the old code where the GPU wouldn't be used. The problem should be fixed now, I believe. Email me if that is not the case.

**Comment by manza-ari** [comment]
Thank you so much for your response. How many total iterations it has?

**Comment by manza-ari** [comment]
Good Day Sir,

Thank you so much for your reply!

When I run main.py, it doesn't use my system gpu's. I also printed
args.cuda which is returning False.

How many total iterations this program has?

Regards,
Kanza

**Comment by gxwangupc** [comment]
> Good Day Sir,
> 
> Thank you so much for your reply!
> 
> When I run main.py, it doesn't use my system gpu's. I also printed
> args.cuda which is returning False.
> 
> How many total iterations this program has?
> 
> Regards,
> Kanza
> …

Hi, just change namespace '--cuda' to
    parser.add_argument('--cuda', default=True, help='If training is to be done on a GPU')

**Comment by gxwangupc** [comment]
Hi, just change namespace '--cuda' to
   parser.add_argument('--cuda', default=True, help='If training is to be done on a GPU')
