### ISSUE TITLE
Problem about the shape of the VAE's output

### ISSUE THREAD

**Issue by yxwang-10** [sinhasam/vaal#21]
Hi

Thanks for your shared code. I am trying to run your code ,but I got some problems. When my VAE input shape is [64, 3, 224, 224], I will get the recon's shape is [3136, 3, 32, 32]. I  think it might be a problem with VAE parameters

**Comment by GWwangshuo** [comment]
@yxwang-10 Please check the source code of the VAE in this repo. Since your input is not cifar10/100, the implementation of VAE should be slightly modified or you can simply reshape your input (3, 244, 244）to (3, 32, 32).

**Comment by yxwang-10** [comment]
@GWwangshuo Thanks very much for your reply. But I noticed that you reported the accuracy on the ImageNet dataset. So if you can tell me your VAE settings on ImageNet, I would be very grateful.

**Comment by GWwangshuo** [comment]
@yxwang-10 I am not the author. For more implementation details, please refer to the orginal paper. The implementation of `β-VAE has the same archite as the Wasserstein autoencoder`. Just simply modify the implementation of VAE.
