### ISSUE TITLE
Question about the trainning time

### ISSUE THREAD

**Issue by kobefang2010** [sinhasam/vaal#3]
Hi sinha
  When I run your code( cifar 10 for example), the trainning time is too long(GTX 1080), which takes about 15 seconds in an iteration(the default number is 100000!) . How to deal with such issue?   Do you terminate the trainning  by setting a new number? 
    Thanks!

**Comment by sinhasam** [comment]
I was able to replicate this. i will optimize the code update it soon.

**Comment by sinhasam** [comment]
should be fixed.

**Comment by lfxx** [comment]
> should be fixed.
So how can i reduce the training time for 100000 iterations are too long!

**Comment by lfxx** [comment]
> Hi sinha
> When I run your code( cifar 10 for example), the trainning time is too long(GTX 1080), which takes about 15 seconds in an iteration(the default number is 100000!) . How to deal with such issue? Do you terminate the trainning by setting a new number?
> Thanks!

Hi,how do you solve this problem?

**Comment by sinhasam** [comment]
To our knowledge this issue is solved. Maybe try getting the most latest version of the repo.

**Comment by lfxx** [comment]
> To our knowledge this issue is solved. Maybe try getting the most latest version of the repo.

I have downloaded the latest version.I run your code( cifar 10), the trainning time is quite long(GTX 1080ti), which takes about 0.75 seconds in an iteration.It will be 21 hours needed to finish 100000 iterations.Is that normal?@sinhasam

**Comment by lfxx** [comment]
> To our knowledge this issue is solved. Maybe try getting the most latest version of the repo.

If i want to replicate your paper,as the splits are defined as :[0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4], i need 6 days to run your code.@sinhasam
