### ISSUE TITLE
Regarding VAE architecture.

### ISSUE THREAD

**Issue by samiksome92** [sinhasam/vaal#32]
Hello,

In the code for VAE the input is 32x32 (CIFAR 10/100) and after the 4 conv layers it reduces to 4x4 (This is also mentioned in comments in the code).

However, in the very next line while flattening the tensor for the fully-connected layer you use View(-1, 1024\*2\*2), whereas it should be View(-1, 1024\*4\*4). 

https://github.com/sinhasam/vaal/blob/67263f32665990a9408430a86df5b6ecd96a812d/model.py#L35

Can you kindly look into this?

**Comment by Liang-ZX** [comment]
32/(2^4)=2. So `View((-1, 1024*2*2))` is right

**Comment by Liang-ZX** [comment]
> Hello,
> 
> In the code for VAE the input is 32x32 (CIFAR 10/100) and after the 4 conv layers it reduces to 4x4 (This is also mentioned in comments in the code).
> 
> However, in the very next line while flattening the tensor for the fully-connected layer you use View(-1, 1024_2_2), whereas it should be View(-1, 1024_4_4).
> 
> https://github.com/sinhasam/vaal/blob/67263f32665990a9408430a86df5b6ecd96a812d/model.py#L35
> 
> Can you kindly look into this?

32/(2^4)=2. So `View((-1, 1024*2*2))` is right

**Comment by samiksome92** [comment]
Ah. I was incorrectly considering those to be output sizes for the conv layers. You are right for 1024x4x4 the input would have to be 64x64. Thank you. I am closing this issue.
